spring:
  datasource:
    url: jdbc:mysql://15.207.207.149:3306/hcms
    username: dev
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-dev.xml 