spring:
  application:
    name: EMS Management System
  profiles:
    active: local

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Kolkata

server:
  port: 8085
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    docExpansion: none
    enabled: true
    operationSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: false
  api-docs:
    enabled: true

app:
  jwt:
    secret: 'b99216f78e5369541457eb679501c510e106417a2a369f936f237f50ed955b7db99216f78e5369541457eb679501c510e106417a2a369f936f237f50ed955b7d'
    expiration: 900000
    refresh-expiration: 86400000